spring.application.name=url-shortener

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true


# Datasource
spring.datasource.url=jdbc:postgresql://${PG_HOST:localhost}:5432/mydatabase?currentSchema=public
spring.datasource.username=myuser
spring.datasource.password=secret



# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


app.base-url=http://localhost:8080